# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import real_time_asr_pb2 as real__time__asr__pb2


class SpeechRecognitionStub(object):
    """音频流识别服务。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeStream = channel.stream_stream(
                '/SpeechRecognition/RecognizeStream',
                request_serializer=real__time__asr__pb2.StreamingSpeechRequest.SerializeToString,
                response_deserializer=real__time__asr__pb2.StreamingSpeechResponse.FromString,
                )


class SpeechRecognitionServicer(object):
    """音频流识别服务。
    """

    def RecognizeStream(self, request_iterator, context):
        """传入metadata "x-api-key"作为验证。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechRecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.RecognizeStream,
                    request_deserializer=real__time__asr__pb2.StreamingSpeechRequest.FromString,
                    response_serializer=real__time__asr__pb2.StreamingSpeechResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SpeechRecognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpeechRecognition(object):
    """音频流识别服务。
    """

    @staticmethod
    def RecognizeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/SpeechRecognition/RecognizeStream',
            real__time__asr__pb2.StreamingSpeechRequest.SerializeToString,
            real__time__asr__pb2.StreamingSpeechResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
